// AUTO-GENERATED by scripts/generate-gallery-data.js
// Do not edit manually

export type YearCategory = '1st Year' | '2nd Year' | '3rd Year' | '4th Year';

export interface GalleryImage {
  id: string;
  src: string;
  category: YearCategory;
  title: string;
}

export const galleryImages: GalleryImage[] = [
  {
    "id": "featured_1",
    "src": "/td2/image2.jpeg",
    "category": "4th Year",
    "title": ""
  },
  {
    "id": "featured_0_1",
    "src": "/td2/image1.jpeg",
    "category": "4th Year",
    "title": ""
  },
  {
    "id": "featured_0_2",
    "src": "/td2/IMG_7794.jpg",
    "category": "2nd Year",
    "title": ""
  },
  {
    "id": "y1_0",
    "src": "/First year photos or any td pics in specified years (File responses)/1681134828036 - Lithik Raj.jpg",
    "category": "1st Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y1_1",
    "src": "/First year photos or any td pics in specified years (File responses)/1697473121755 - Niranjan Devana.jpg",
    "category": "1st Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y1_2",
    "src": "/First year photos or any td pics in specified years (File responses)/1697473121790 - Niranjan Devana.jpg",
    "category": "1st Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y1_3",
    "src": "/First year photos or any td pics in specified years (File responses)/1697473121803 - Niranjan Devana.jpg",
    "category": "1st Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y1_4",
    "src": "/First year photos or any td pics in specified years (File responses)/1697473121838 - Niranjan Devana.jpg",
    "category": "1st Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y1_5",
    "src": "/First year photos or any td pics in specified years (File responses)/1697473121878 - Niranjan Devana.jpg",
    "category": "1st Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y1_6",
    "src": "/First year photos or any td pics in specified years (File responses)/1697473121909 - Niranjan Devana.jpg",
    "category": "1st Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y1_7",
    "src": "/First year photos or any td pics in specified years (File responses)/1697473399663 - Niranjan Devana.jpg",
    "category": "1st Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y1_8",
    "src": "/First year photos or any td pics in specified years (File responses)/1713550338289 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_9",
    "src": "/First year photos or any td pics in specified years (File responses)/20221217_154512 - Mahitha Penkey.jpg",
    "category": "1st Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y1_10",
    "src": "/First year photos or any td pics in specified years (File responses)/742AE85E-B6EB-47F9-9108-F5D324B9A559 - Kondakala Priyanka.JPG",
    "category": "1st Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y1_11",
    "src": "/First year photos or any td pics in specified years (File responses)/a - RASAMALLA MEGHANA.jpeg",
    "category": "1st Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y1_12",
    "src": "/First year photos or any td pics in specified years (File responses)/b - RASAMALLA MEGHANA.jpeg",
    "category": "1st Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y1_13",
    "src": "/First year photos or any td pics in specified years (File responses)/c - RASAMALLA MEGHANA.jpeg",
    "category": "1st Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y1_14",
    "src": "/td2/image1.jpeg",
    "category": "4th Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y1_15",
    "src": "/First year photos or any td pics in specified years (File responses)/e - RASAMALLA MEGHANA.jpeg",
    "category": "1st Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y1_16",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20221210-WA0007 - Murali Krishna.jpg",
    "category": "1st Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y1_17",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20221217-WA0008 - Kanth Balla.jpg",
    "category": "1st Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y1_18",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20221218-WA0018 - Mahitha Penkey.jpg",
    "category": "1st Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y1_19",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20221218-WA0021 - Mahitha Penkey(1).jpg",
    "category": "1st Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y1_20",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20230204-WA0004 - Mahitha Penkey.jpg",
    "category": "1st Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y1_21",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20230204-WA0005 - Mahitha Penkey.jpg",
    "category": "1st Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y1_22",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20230427-WA0072 - Nagaraj Gatla.jpg",
    "category": "1st Year",
    "title": "Nagaraj Gatla"
  },
  {
    "id": "y1_23",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20230427-WA0080 - Kanth Balla.jpg",
    "category": "1st Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y1_24",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20230427-WA0080 - Mahitha Penkey.jpg",
    "category": "1st Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y1_25",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20230427-WA0090 - Mahitha Penkey.jpg",
    "category": "1st Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y1_26",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20230427-WA0104 - Koushik Allada.jpg",
    "category": "1st Year",
    "title": "Koushik Allada"
  },
  {
    "id": "y1_27",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20231210-WA0000 - Murali Krishna.jpg",
    "category": "1st Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y1_28",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20240419-WA0249 - Maloth Lavanya.jpg",
    "category": "1st Year",
    "title": "Maloth Lavanya"
  },
  {
    "id": "y1_29",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20240420-WA0018 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_30",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20240709-WA0060 - M Likith Mahendra(1).jpg",
    "category": "1st Year",
    "title": "M Likith Mahendra"
  },
  {
    "id": "y1_31",
    "src": "/td2/image2.jpeg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_32",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20250505-WA0023 - M Likith Mahendra.jpg",
    "category": "1st Year",
    "title": "M Likith Mahendra"
  },
  {
    "id": "y1_33",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20250630-WA0048 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_34",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20250630-WA0049 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_35",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20251211-WA0006 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_36",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260402-WA0000 - Mohammed Abubaker.jpg",
    "category": "1st Year",
    "title": "Mohammed Abubaker"
  },
  {
    "id": "y1_37",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260403-WA0031 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_38",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0026 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_39",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0030 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_40",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0043 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_41",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0044 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_42",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0045 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_43",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0047 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_44",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0048 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_45",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0049 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_46",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0050 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_47",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0051 - Hemasri Podakanti.jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_48",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0052 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_49",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0057 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_50",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0060 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_51",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0235 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_52",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG-20260404-WA0249 - Hemasri Podakanti(1).jpg",
    "category": "1st Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y1_53",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG20240419130339 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_54",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG20240419132840 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_55",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG20240419133648 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_56",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG20240419133805 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_57",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG20240419134004 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_58",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG20240419150030 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_59",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG20240419150150_01 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_60",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG20240419150517 - Lohith Lakkakula.jpg",
    "category": "1st Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y1_61",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_0231 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_62",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_0266 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_63",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_0275 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_64",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_0367 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_65",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_0371 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_66",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_0789 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_67",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_0834 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_68",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_1202 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_69",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_1730 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "1st Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y1_70",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230427_114421~2 - Jeevan Ajmeera.jpg",
    "category": "1st Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y1_71",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230427_115555 - Jeevan Ajmeera.jpg",
    "category": "1st Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y1_72",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230427_125143 - Jeevan Ajmeera.jpg",
    "category": "1st Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y1_73",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230427_131525 (1) - Jeevan Ajmeera.jpg",
    "category": "1st Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y1_74",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230427_145711 - Jeevan Ajmeera.jpg",
    "category": "1st Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y1_75",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230427_150130 - Jeevan Ajmeera.jpg",
    "category": "1st Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y1_76",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230427_215026-01 - Lithik Raj.jpeg",
    "category": "1st Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y1_77",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230427_223309_678 - Kanth Balla.jpg",
    "category": "1st Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y1_78",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_20230428_121929_717 - Kanth Balla.jpg",
    "category": "1st Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y1_79",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_2702 - Kondakala Priyanka.JPG",
    "category": "1st Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y1_80",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_4595 - Kondakala Priyanka.JPG",
    "category": "1st Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y1_81",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_5449 - Kondakala Priyanka.JPG",
    "category": "1st Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y1_82",
    "src": "/First year photos or any td pics in specified years (File responses)/IMG_5452 - Kondakala Priyanka.JPG",
    "category": "1st Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y1_83",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230427_220243706 - Koushik Allada.jpg",
    "category": "1st Year",
    "title": "Koushik Allada"
  },
  {
    "id": "y1_84",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230427_221451869 - Koushik Allada.jpg",
    "category": "1st Year",
    "title": "Koushik Allada"
  },
  {
    "id": "y1_85",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230427_230050060 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_86",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230427_232111749 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_87",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230427_233732246 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_88",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230427_235054214 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_89",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230429_114322619 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_90",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230429_114618315 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_91",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230430_020656509 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_92",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230430_020709856 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_93",
    "src": "/First year photos or any td pics in specified years (File responses)/InShot_20230430_020831420 - Pradeep Kumar.jpg",
    "category": "1st Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y1_94",
    "src": "/First year photos or any td pics in specified years (File responses)/Screenshot_20230427_184055_Snapchat - Mahitha Penkey.jpg",
    "category": "1st Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y1_95",
    "src": "/First year photos or any td pics in specified years (File responses)/Screenshot_20260402_152018_Photos - EDHA MEGHANA.jpg",
    "category": "1st Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y1_96",
    "src": "/First year photos or any td pics in specified years (File responses)/Screenshot_20260402_152218_Photos - EDHA MEGHANA(1).jpg",
    "category": "1st Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y1_97",
    "src": "/First year photos or any td pics in specified years (File responses)/Screenshot_20260402_152419_Photos - EDHA MEGHANA(1).jpg",
    "category": "1st Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y1_98",
    "src": "/First year photos or any td pics in specified years (File responses)/Snapchat-492293130 - Pavani Reddy.jpg",
    "category": "1st Year",
    "title": "Pavani Reddy"
  },
  {
    "id": "y1_99",
    "src": "/First year photos or any td pics in specified years (File responses)/Snapchat-552870545 - NEELAM SINDHU.jpg",
    "category": "1st Year",
    "title": "NEELAM SINDHU"
  },
  {
    "id": "y1_100",
    "src": "/First year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 10.24.51 PM - BOLEM MOUNIKA.jpeg",
    "category": "1st Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y1_101",
    "src": "/First year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 10.30.08 PM - BOLEM MOUNIKA.jpeg",
    "category": "1st Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y1_102",
    "src": "/First year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 10.34.18 PM - BOLEM MOUNIKA.jpeg",
    "category": "1st Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y2_103",
    "src": "/Second  year photos or any td pics in specified years (File responses)/1713535490618 - Lithik Raj.jpg",
    "category": "2nd Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y2_104",
    "src": "/Second  year photos or any td pics in specified years (File responses)/20240419_114529 - Mahitha Penkey.jpg",
    "category": "2nd Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y2_105",
    "src": "/Second  year photos or any td pics in specified years (File responses)/20240419_114617 - Mahitha Penkey.jpg",
    "category": "2nd Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y2_106",
    "src": "/Second  year photos or any td pics in specified years (File responses)/20240419_114618 - Mahitha Penkey.jpg",
    "category": "2nd Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y2_107",
    "src": "/Second  year photos or any td pics in specified years (File responses)/20240419_114702 - Mahitha Penkey.jpg",
    "category": "2nd Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y2_108",
    "src": "/Second  year photos or any td pics in specified years (File responses)/20240419_122358 - Murali Krishna.jpg",
    "category": "2nd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y2_109",
    "src": "/Second  year photos or any td pics in specified years (File responses)/20240420_220939 - Murali Krishna.jpg",
    "category": "2nd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y2_110",
    "src": "/Second  year photos or any td pics in specified years (File responses)/f - RASAMALLA MEGHANA.jpeg",
    "category": "2nd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y2_111",
    "src": "/Second  year photos or any td pics in specified years (File responses)/g - RASAMALLA MEGHANA.jpeg",
    "category": "2nd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y2_112",
    "src": "/Second  year photos or any td pics in specified years (File responses)/h - RASAMALLA MEGHANA.jpeg",
    "category": "2nd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y2_113",
    "src": "/Second  year photos or any td pics in specified years (File responses)/i - RASAMALLA MEGHANA.jpeg",
    "category": "2nd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y2_114",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20230503-WA0019 - Murali Krishna.jpg",
    "category": "2nd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y2_115",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240125-WA0025 - M Likith Mahendra(1).jpg",
    "category": "2nd Year",
    "title": "M Likith Mahendra"
  },
  {
    "id": "y2_116",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0014 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_117",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0023 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_118",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0064 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_119",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0088 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_120",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0089 - Kanth Balla.jpg",
    "category": "2nd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y2_121",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0120 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_122",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0132 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_123",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0136 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_124",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0160 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_125",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240419-WA0187 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_126",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240421-WA0004 - Kanth Balla.jpg",
    "category": "2nd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y2_127",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240421-WA0005 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_128",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240421-WA0019 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_129",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240421-WA0060 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_130",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240421-WA0081 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_131",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240422-WA0012 - M Likith Mahendra(1).jpg",
    "category": "2nd Year",
    "title": "M Likith Mahendra"
  },
  {
    "id": "y2_132",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240503-WA0054 - Murali Krishna.jpg",
    "category": "2nd Year",
    "title": "Murali Krishna"
  },
  /* {
     "id": "y2_133",
     "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20240704-WA0011 - M Likith Mahendra(1).jpg",
     "category": "2nd Year",
     "title": "M Likith Mahendra"
   },*/
  {
    "id": "y2_134",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20241213-WA0218 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_135",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20250417-WA0071 - Maloth Lavanya.jpg",
    "category": "2nd Year",
    "title": "Maloth Lavanya"
  },
  {
    "id": "y2_136",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20250912-WA0085 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_137",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20251211-WA0010 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_138",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260402-WA0000 - Mohammed Abubaker.jpg",
    "category": "2nd Year",
    "title": "Mohammed Abubaker"
  },
  {
    "id": "y2_139",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260403-WA0018 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_140",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260403-WA0029 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_141",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260403-WA0031 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_142",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0032 - NEELAM SINDHU.jpg",
    "category": "2nd Year",
    "title": "NEELAM SINDHU"
  },
  {
    "id": "y2_143",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0055 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_144",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0056 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_145",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0057 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_146",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0058 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_147",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0060 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_148",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0061 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_149",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0062 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_150",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0063 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_151",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0064 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_152",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0065 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_153",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0250 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_154",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0251 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_155",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0252 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_156",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0253 - Hemasri Podakanti(1).jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_157",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG-20260404-WA0254 - Hemasri Podakanti.jpg",
    "category": "2nd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y2_158",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240419113631 - Pavani Reddy.jpg",
    "category": "2nd Year",
    "title": "Pavani Reddy"
  },
  {
    "id": "y2_159",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240419115032 - M Likith Mahendra(1).jpg",
    "category": "2nd Year",
    "title": "M Likith Mahendra"
  },
  {
    "id": "y2_160",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240419132814 - Kanth Balla.jpg",
    "category": "2nd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y2_161",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240419133856 - Kanth Balla.jpg",
    "category": "2nd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y2_162",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240419162154 - Murali Krishna.jpg",
    "category": "2nd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y2_163",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240419162258 - Murali Krishna.jpg",
    "category": "2nd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y2_164",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240420195931 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_165",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240420195932 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_166",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240420200240 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_167",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240420200337 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_168",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240420200858 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_169",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG20240420202721 - Lohith Lakkakula.jpg",
    "category": "2nd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y2_170",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_20240419_115457 - Jeevan Ajmeera.jpg",
    "category": "2nd Year",
    "title": "Jeevan Ajmeera"
  },
  {
    "id": "y2_171",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_20240704_223411 - Lithik Raj.jpg",
    "category": "2nd Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y2_172",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_20240820_142457_264 - M Likith Mahendra(1).jpg",
    "category": "2nd Year",
    "title": "M Likith Mahendra"
  },
  {
    "id": "y2_173",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_5395_Original - Kondakala Priyanka.jpg",
    "category": "2nd Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y2_174",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_5453 - Kondakala Priyanka.JPG",
    "category": "2nd Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y2_175",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_5454 - Kondakala Priyanka.JPG",
    "category": "2nd Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y2_176",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_7095 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "2nd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y2_177",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_7111 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "2nd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y2_178",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_7114 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "2nd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y2_179",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_7150 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "2nd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y2_180",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_7158 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "2nd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y2_181",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_7190 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "2nd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y2_182",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_7618 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "2nd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y2_183",
    "src": "/Second  year photos or any td pics in specified years (File responses)/IMG_7723 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "2nd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y2_184",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20231024_011242601 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_185",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20231024_011309292 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_186",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20240201_083718828 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_187",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20240422_170724993 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_188",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20240422_170746654 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_189",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20240422_170900292 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_190",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20240422_172624643 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_191",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20240422_172844376 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_192",
    "src": "/Second  year photos or any td pics in specified years (File responses)/InShot_20240521_140137644 - Pradeep Kumar.jpg",
    "category": "2nd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y2_193",
    "src": "/Second  year photos or any td pics in specified years (File responses)/j - RASAMALLA MEGHANA.jpeg",
    "category": "2nd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y2_194",
    "src": "/Second  year photos or any td pics in specified years (File responses)/k - RASAMALLA MEGHANA.jpeg",
    "category": "2nd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y2_195",
    "src": "/Second  year photos or any td pics in specified years (File responses)/l - RASAMALLA MEGHANA.jpeg",
    "category": "2nd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y2_196",
    "src": "/Second  year photos or any td pics in specified years (File responses)/Screenshot_20260402-031222_Instagram~2 - Preetham Preetham.png",
    "category": "2nd Year",
    "title": "Preetham Preetham"
  },
  {
    "id": "y2_197",
    "src": "/Second  year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 10.14.38 PM - BOLEM MOUNIKA.jpeg",
    "category": "2nd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y2_198",
    "src": "/Second  year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 10.17.25 PM - BOLEM MOUNIKA.jpeg",
    "category": "2nd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y2_199",
    "src": "/Second  year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 10.25.36 PM - BOLEM MOUNIKA.jpeg",
    "category": "2nd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y2_200",
    "src": "/Second  year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.30.12 PM - BOLEM MOUNIKA.jpeg",
    "category": "2nd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y2_201",
    "src": "/Second  year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.31.17 PM - BOLEM MOUNIKA.jpeg",
    "category": "2nd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y3_202",
    "src": "/Third year photos or any td pics in specified years (File responses)/1699498758586 - Lithik Raj.jpg",
    "category": "3rd Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y3_203",
    "src": "/Third year photos or any td pics in specified years (File responses)/1730737400218 - Lithik Raj.jpg",
    "category": "3rd Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y3_204",
    "src": "/Third year photos or any td pics in specified years (File responses)/1744868922576 - Niranjan Devana.jpg",
    "category": "3rd Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y3_205",
    "src": "/Third year photos or any td pics in specified years (File responses)/5C25E92A-59FC-480A-9C5B-AEF5C74FC356 - Kondakala Priyanka.JPG",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y3_206",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20240428-WA0016 - Murali Krishna.jpg",
    "category": "3rd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y3_207",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20240709-WA0000 - Lohith Lakkakula.jpg",
    "category": "3rd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y3_208",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20240727-WA0005 - Lohith Lakkakula.jpg",
    "category": "3rd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y3_209",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250404-WA0006 - Murali Krishna.jpg",
    "category": "3rd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y3_210",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250406-WA0002 - Murali Krishna.jpg",
    "category": "3rd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y3_211",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250408-WA0008 - Murali Krishna.jpg",
    "category": "3rd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y3_212",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250415-WA0080 - Kanth Balla.jpg",
    "category": "3rd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y3_213",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250415-WA0087 - Kanth Balla.jpg",
    "category": "3rd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y3_214",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250415-WA0159 - Mayuri Gongalla.jpg",
    "category": "3rd Year",
    "title": "Mayuri Gongalla"
  },
  {
    "id": "y3_215",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250415-WA0622 - Hemasri Podakanti(1).jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_216",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250416-WA0002 - Murali Krishna.jpg",
    "category": "3rd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y3_217",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250417-WA0005 - Murali Krishna.jpg",
    "category": "3rd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y3_218",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250417-WA0044 - Kanth Balla.jpg",
    "category": "3rd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y3_219",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250417-WA0048 - Kanth Balla.jpg",
    "category": "3rd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y3_220",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250417-WA0205 - Mayuri Gongalla.jpg",
    "category": "3rd Year",
    "title": "Mayuri Gongalla"
  },
  {
    "id": "y3_221",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250418-WA0003 - Murali Krishna.jpg",
    "category": "3rd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y3_222",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250418-WA0004 - Murali Krishna.jpg",
    "category": "3rd Year",
    "title": "Murali Krishna"
  },
  {
    "id": "y3_223",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250418-WA0005 - Mahitha Penkey.jpg",
    "category": "3rd Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y3_224",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250418-WA0008 - Mahitha Penkey.jpg",
    "category": "3rd Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y3_225",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250421-WA0000 - Mahitha Penkey.jpg",
    "category": "3rd Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y3_226",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250523-WA0023 - Mahitha Penkey.jpg",
    "category": "3rd Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y3_227",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250913-WA0000 - Kanth Balla.jpg",
    "category": "3rd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y3_228",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20250913-WA0012 - Kanth Balla.jpg",
    "category": "3rd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y3_229",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20251108-WA0055 - Hemasri Podakanti(1).jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_230",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20251116-WA0253 - Hemasri Podakanti(1).jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_231",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260313-WA0143 - Maloth Lavanya.jpg",
    "category": "3rd Year",
    "title": "Maloth Lavanya"
  },
  {
    "id": "y3_232",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260403-WA0019 - Hemasri Podakanti(1).jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_233",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260403-WA0029 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_234",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260403-WA0034 - Hemasri Podakanti(1).jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_235",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0066 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_236",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0067 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_237",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0068 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_238",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0069 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_239",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0072 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_240",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0073 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_241",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0074 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_242",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0075 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_243",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0076 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_244",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0254 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_245",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0255 - Hemasri Podakanti(1).jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_246",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0256 - Hemasri Podakanti(1).jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_247",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0257 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_248",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0258 - Hemasri Podakanti(1).jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_249",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG-20260404-WA0260 - Hemasri Podakanti.jpg",
    "category": "3rd Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y3_250",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG20250415121901 - Preetham Preetham.jpg",
    "category": "3rd Year",
    "title": "Preetham Preetham"
  },
  {
    "id": "y3_251",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG20250415161226 - Kanth Balla.jpg",
    "category": "3rd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y3_252",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_1471 - Kondakala Priyanka.JPG",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y3_253",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_20240615_183339 - Lohith Lakkakula.jpg",
    "category": "3rd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y3_254",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_20241104_221220 - Lithik Raj.jpg",
    "category": "3rd Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y3_255",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_20250416_183030 - Niranjan Devana.jpg",
    "category": "3rd Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y3_256",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_20250416_183505 - Niranjan Devana.jpg",
    "category": "3rd Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y3_257",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_20251111_211653 - Niranjan Devana.jpg",
    "category": "3rd Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y3_258",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_20251111_211732 - Niranjan Devana.jpg",
    "category": "3rd Year",
    "title": "Niranjan Devana"
  },
  {
    "id": "y3_259",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_20260214_231716_590 - M Likith Mahendra(1).jpg",
    "category": "3rd Year",
    "title": "M Likith Mahendra"
  },
  /*{
    "id": "y3_260",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_2045_Original - Kondakala Priyanka.jpg",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },*/
  {
    "id": "y3_261",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_2297 - Kondakala Priyanka.JPG",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y3_262",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3419 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_263",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3594 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_264",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3642 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_265",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3665 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_266",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3749 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_267",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3765 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_268",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3772 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_269",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3806 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_270",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_3821 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_271",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_4170 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "3rd Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y3_272",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_4613_Original - Kondakala Priyanka.jpg",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },
  /*{
    "id": "y3_273",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_5457 - Kondakala Priyanka.JPG",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y3_274",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_5459 - Kondakala Priyanka.JPG",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },*/
  {
    "id": "y3_275",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_5461 - Kondakala Priyanka.JPG",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },
  /*{
    "id": "y3_276",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_5462 - Kondakala Priyanka.JPG",
    "category": "3rd Year",
    "title": "Kondakala Priyanka"
  },*/
  {
    "id": "y3_277",
    "src": "/Third year photos or any td pics in specified years (File responses)/IMG_7143 - Kanth Balla.JPG",
    "category": "3rd Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y3_278",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20241223_180354621 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_279",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250203_230925597 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_280",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250418_192522362 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_281",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250420_152421629 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_282",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250420_152612016 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_283",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250420_153450760 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_284",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250427_162231734 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_285",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250427_162324160 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_286",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250427_162346078 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_287",
    "src": "/Third year photos or any td pics in specified years (File responses)/InShot_20250427_162536816 - Pradeep Kumar.jpg",
    "category": "3rd Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y3_288",
    "src": "/Third year photos or any td pics in specified years (File responses)/o - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_289",
    "src": "/Third year photos or any td pics in specified years (File responses)/p - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_290",
    "src": "/Third year photos or any td pics in specified years (File responses)/q - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_291",
    "src": "/Third year photos or any td pics in specified years (File responses)/r - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_292",
    "src": "/Third year photos or any td pics in specified years (File responses)/s - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_293",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_2025-07-02-16-29-15-35_965bbf4d18d205f782c6b8409c5773a4 - Lohith Lakkakula.jpg",
    "category": "3rd Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y3_294",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_124841_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_295",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_150210_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_296",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_150251_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_297",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_150346_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_298",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_150635_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_299",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_150650_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_300",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_151125_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_301",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_151157_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_302",
    "src": "/Third year photos or any td pics in specified years (File responses)/Screenshot_20260402_151443_Photos - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_303",
    "src": "/Third year photos or any td pics in specified years (File responses)/Snapchat-1897270319 - EDHA MEGHANA(1).jpg",
    "category": "3rd Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y3_304",
    "src": "/Third year photos or any td pics in specified years (File responses)/t - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_305",
    "src": "/Third year photos or any td pics in specified years (File responses)/u - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_306",
    "src": "/Third year photos or any td pics in specified years (File responses)/v - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_307",
    "src": "/Third year photos or any td pics in specified years (File responses)/w - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y3_308",
    "src": "/Third year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.01.54 PM - BOLEM MOUNIKA.jpeg",
    "category": "3rd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y3_309",
    "src": "/Third year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.02.22 PM - BOLEM MOUNIKA.jpeg",
    "category": "3rd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y3_310",
    "src": "/Third year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.04.07 PM - BOLEM MOUNIKA.jpeg",
    "category": "3rd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y3_311",
    "src": "/Third year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.06.21 PM - BOLEM MOUNIKA.jpeg",
    "category": "3rd Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y3_312",
    "src": "/Third year photos or any td pics in specified years (File responses)/x - RASAMALLA MEGHANA.jpeg",
    "category": "3rd Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y4_313",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/09588636-5cb4-4a6c-9920-484eac29b859 - Kondakala Priyanka.JPG",
    "category": "4th Year",
    "title": "Kondakala Priyanka"
  },
  {
    "id": "y4_314",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/1771334723091 - Lithik Raj.jpg",
    "category": "4th Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y4_315",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/20260314_203501 - Mahitha Penkey.jpg",
    "category": "4th Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y4_316",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/20260314_211447 - Mahitha Penkey.jpg",
    "category": "4th Year",
    "title": "Mahitha Penkey"
  },
  {
    "id": "y4_317",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/aa - RASAMALLA MEGHANA.jpeg",
    "category": "4th Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y4_318",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/bb - RASAMALLA MEGHANA.jpeg",
    "category": "4th Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y4_319",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20250912-WA0078 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_320",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0017 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_321",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0020 - Lohith Lakkakula.jpg",
    "category": "4th Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y4_322",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0029 - Kanth Balla.jpg",
    "category": "4th Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y4_323",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0080 - Kanth Balla.jpg",
    "category": "4th Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y4_324",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0090 - Lohith Lakkakula.jpg",
    "category": "4th Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y4_325",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0098 - Kanth Balla.jpg",
    "category": "4th Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y4_326",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0102 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_327",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0103 - Lohith Lakkakula.jpg",
    "category": "4th Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y4_328",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0118 - Kanth Balla(1).jpg",
    "category": "4th Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y4_329",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0124 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_330",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0125 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_331",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0138 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_332",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0188 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_333",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0301 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_334",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0302 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_335",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0334 - M Likith Mahendra(1).jpg",
    "category": "4th Year",
    "title": "M Likith Mahendra"
  },
  {
    "id": "y4_336",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0350 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_337",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0542 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_338",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0597 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_339",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260313-WA0625 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_340",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260314-WA0102 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_341",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260314-WA0726 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_342",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260314-WA1120 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_343",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260315-WA0058 - Kanth Balla.jpg",
    "category": "4th Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y4_344",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260315-WA0068 - Kanth Balla.jpg",
    "category": "4th Year",
    "title": "Kanth Balla"
  },
  {
    "id": "y4_345",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260315-WA0114 - Maloth Lavanya.jpg",
    "category": "4th Year",
    "title": "Maloth Lavanya"
  },
  {
    "id": "y4_346",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260315-WA0178 - Mayuri Gongalla.jpg",
    "category": "4th Year",
    "title": "Mayuri Gongalla"
  },
  {
    "id": "y4_347",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260315-WA0239 - EDHA MEGHANA(1).jpg",
    "category": "4th Year",
    "title": "EDHA MEGHANA"
  },
  {
    "id": "y4_348",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260330-WA0043 - B Krishna.jpg",
    "category": "4th Year",
    "title": "B Krishna"
  },
  {
    "id": "y4_349",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260403-WA0015 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_350",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260403-WA0016 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_351",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260403-WA0017 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_352",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0079 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_353",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0080 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_354",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0081 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_355",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0084 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_356",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0085 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_357",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0088 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_358",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0090 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_359",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0091 - Hemasri Podakanti.jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_360",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0259 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_361",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG-20260404-WA0260 - Hemasri Podakanti(1).jpg",
    "category": "4th Year",
    "title": "Hemasri Podakanti"
  },
  {
    "id": "y4_362",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_20260313_192426_564 - Lithik Raj.jpg",
    "category": "4th Year",
    "title": "Lithik Raj"
  },
  {
    "id": "y4_363",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_20260313_200402 - Lohith Lakkakula.jpg",
    "category": "4th Year",
    "title": "Lohith Lakkakula"
  },
  {
    "id": "y4_364",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_20260314_105038319_HDR_PORTRAIT - Preetham Preetham.jpg",
    "category": "4th Year",
    "title": "Preetham Preetham"
  },
  {
    "id": "y4_365",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_20260314_110117765_HDR_PORTRAIT - Preetham Preetham.jpg",
    "category": "4th Year",
    "title": "Preetham Preetham"
  },
  {
    "id": "y4_366",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6389 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_367",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6397 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_368",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6423 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_369",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6435 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_370",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6502 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_371",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6546 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_372",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6836 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_373",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6852 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_374",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6864 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_375",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/IMG_6873 - PERUGU PAVAN SRI MANIKANTA.jpeg",
    "category": "4th Year",
    "title": "PERUGU PAVAN SRI MANIKANTA"
  },
  {
    "id": "y4_376",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20251101_225126962 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_377",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260228_214255942 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_378",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260316_205706419 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_379",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260316_205732640 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_380",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260316_205758770 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_381",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260316_210822837 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_382",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260316_211158131 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_383",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260316_211221803 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_384",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260316_211449239 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_385",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/InShot_20260316_211556736 - Pradeep Kumar.jpg",
    "category": "4th Year",
    "title": "Pradeep Kumar"
  },
  {
    "id": "y4_386",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/mm - RASAMALLA MEGHANA.jpeg",
    "category": "4th Year",
    "title": "RASAMALLA MEGHANA"
  },
  {
    "id": "y4_387",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/motion_photo_5223220243087967119 - Pavani Reddy.jpg",
    "category": "4th Year",
    "title": "Pavani Reddy"
  },
  {
    "id": "y4_388",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/Screenshot_2026-04-04-11-47-22-38_99c04817c0de5652397fc8b56c3b3817 - NEELAM SINDHU.jpg",
    "category": "4th Year",
    "title": "NEELAM SINDHU"
  },
  {
    "id": "y4_389",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 10.20.33 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_390",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 10.27.43 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_391",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.00.30 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_392",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.05.13 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_393",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.05.41 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_394",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.13.56 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_395",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.14.12 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_396",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.14.52 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_397",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/WhatsApp Image 2026-04-02 at 11.30.42 PM - BOLEM MOUNIKA.jpeg",
    "category": "4th Year",
    "title": "BOLEM MOUNIKA"
  },
  {
    "id": "y4_398",
    "src": "/Fourth year photos or any td pics in specified years (File responses)/z - RASAMALLA MEGHANA.jpeg",
    "category": "4th Year",
    "title": "RASAMALLA MEGHANA"
  }
];
